const express = require('express');
const mongoose = require('mongoose');

const bodyParser = require("body-parser");
const passport = require('passport');

const users = require("./routes/api/users");
const publications = require("./routes/api/publications");

const swaggerUi = require('swagger-ui-express');
var swaggerJsdoc = require("swagger-jsdoc");
///const swaggerDocument = require('./swagger.json');

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: "API",
      version: "1.0.0",
      description: "Test Express API with autogenerated swagger doc"
    }
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ["./routes/api/users.js", ]
};

const specs = swaggerJsdoc(options);


require('dotenv').config();

const app = express();

// Body parser middleware
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

// DB Config
const db = require('./config/keys').mongoURI;

// Connect to MongoDB
mongoose
  .connect(db, { useUnifiedTopology: true , useNewUrlParser: true })
  .then(() => console.log('MongoDB Connected'))
  .catch(err => console.log(err));

// Passport middleware
app.use(passport.initialize());
// Passport Config
require('./config/passport')(passport);

app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
// Use Routes
users.setup(app);
publications.setup(app);
//app.use('/api/users', users);
// app.use('/api/profile', profile);
// app.use('/api/posts', posts);

const port = process.env.PORT || 5000;

app.listen(port, () => console.log(`Server running on port ${port}`));


 
//app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(swaggerDocument));
// app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(specs));
